using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using SolidWorks.Interop.sldworks;

namespace ADDIN.Commands.MirrorV7
{
    public sealed class CrossDocumentReferenceResultV7
    {
        public int Attempted { get; set; }
        public int Resolved { get; set; }
        public int Unavailable { get; set; }
        public int Mismatched { get; set; }
        public int Ambiguous { get; set; }
        public int SystemSkipped { get; set; }
        public bool Success { get { return Attempted > 0 && Resolved == Attempted && Unavailable == 0 && Mismatched == 0 && Ambiguous == 0; } }
    }

    public static class CrossDocumentReferenceAuditV7
    {
        public static CrossDocumentReferenceResultV7 Run(MirrorV7ModelGraph sourceGraph, ModelDoc2 copy,
            IReadOnlyDictionary<int, PersistReferenceV7> replacements = null,
            IReadOnlyDictionary<int, string> replacementTargetNames = null)
        {
            if (sourceGraph == null) throw new ArgumentNullException("sourceGraph");
            if (copy == null) throw new ArgumentNullException("copy");
            CrossDocumentReferenceResultV7 result = new CrossDocumentReferenceResultV7();
            foreach (MirrorV7FeatureNode node in sourceGraph.Nodes)
            {
                if (node != null && node.Role == MirrorV7FeatureRole.System) { result.SystemSkipped++; continue; }
                result.Attempted++;
                if (node == null || node.PersistentReference == null) { result.Unavailable++; MirrorV7Diagnostics.Log("[PHASE6A][SOURCE_REFERENCE_UNAVAILABLE]"); continue; }
                try
                {
                    int state;
                    PersistReferenceV7 replacement = null;
                    bool recreated = replacements != null &&
                        replacements.TryGetValue(node.TreeOrder, out replacement);
                    object raw = PersistentReferenceServiceV7.Resolve(copy,
                        recreated ? replacement : node.PersistentReference, out state);
                    Feature feature = raw as Feature;
                    if (raw == null) { result.Unavailable++; MirrorV7Diagnostics.Log("[PHASE6A][COPY_RESOLVE_NULL] name=\"" + node.Name + "\" state=" + state); continue; }
                    if (feature == null) { result.Mismatched++; MirrorV7Diagnostics.Log("[PHASE6A][COPY_TYPE_MISMATCH] name=\"" + node.Name + "\" state=" + state); continue; }
                    string type2, type1;
                    string actualName = feature.Name ?? "", actualType = FeatureTypeHelperV7.GetEffectiveType(feature, out type2, out type1);
                    MirrorV7Diagnostics.Log("[PHASE6A][TYPE_CHECK] expectedName=\"" + node.Name + "\" actualName=\"" + actualName + "\" expectedType=\"" + node.TypeName + "\" rawType2=\"" + type2 + "\" rawType1=\"" + type1 + "\" effectiveType=\"" + actualType + "\" state=" + state + " nativeReplacement=" + recreated);
                    string expectedName = node.Name ?? "";
                    string registeredName;
                    if (replacementTargetNames != null && replacementTargetNames.TryGetValue(node.TreeOrder, out registeredName))
                    {
                        if (!recreated || node.Role != MirrorV7FeatureRole.Sketch || string.IsNullOrWhiteSpace(registeredName))
                            throw new InvalidOperationException("FLANGE51 invalid replacement name registration: " + node.Name);
                        expectedName = registeredName;
                        MirrorV7Diagnostics.Log("[FLANGE51][REPLACEMENT_NAME_AUDIT] source=" + node.Name +
                            " registeredTarget=" + expectedName + " resolvedTarget=" + actualName);
                    }
                    bool nameMatches = string.Equals(expectedName, actualName, StringComparison.Ordinal);
                    bool typeMatches = string.Equals(node.TypeName ?? "", actualType, StringComparison.Ordinal);

                    // Flat-pattern names are generated by SOLIDWORKS. Rebuild/save may legally
                    // renumber the suffix (for example FlatPattern12 -> FlatPattern35) even
                    // though the persistent reference still resolves to the same feature.
                    // Accept only this known system rename; the effective type and persistent
                    // reference must still match, so a wrong user feature cannot pass the gate.
                    bool isGeneratedFlatPatternRename =
                        typeMatches &&
                        node.Role == MirrorV7FeatureRole.SheetMetal &&
                        string.Equals(actualType, "FlatPattern", StringComparison.OrdinalIgnoreCase);

                    if (!typeMatches || (!nameMatches && !isGeneratedFlatPatternRename))
                    {
                        result.Mismatched++;
                        MirrorV7Diagnostics.Log("[PHASE6A][COPY_IDENTITY_MISMATCH] expected=\"" + node.Name + "\" actual=\"" + actualName + "\" expectedType=\"" + node.TypeName + "\" actualType=\"" + actualType + "\" state=" + state);
                        continue;
                    }

                    if (!nameMatches)
                    {
                        MirrorV7Diagnostics.Log("[PHASE6A][SYSTEM_RENAME_ACCEPTED] expected=\"" + node.Name + "\" actual=\"" + actualName + "\" type=\"" + actualType + "\" state=" + state);
                    }
                    result.Resolved++; MirrorV7Diagnostics.Log("[PHASE6A][COPY_RESOLVE_OK] name=\"" + node.Name + "\" type=\"" + actualType + "\" state=" + state);
                }
                catch (Exception ex) { result.Unavailable++; MirrorV7Diagnostics.Log("[PHASE6A][COPY_RESOLVE_EXCEPTION] name=\"" + node.Name + "\" message=" + ex.Message); }
            }
            MirrorV7Diagnostics.Log("[PHASE6A][REFERENCE_SUMMARY] attempted=" + result.Attempted + " resolved=" + result.Resolved + " unavailable=" + result.Unavailable + " mismatched=" + result.Mismatched + " ambiguous=" + result.Ambiguous + " systemSkipped=" + result.SystemSkipped);
            return result;
        }
    }

    public sealed class ExternalDependencyAuditResultV7
    {
        public int Total { get; set; }
        public int AllowedSheetMetalResources { get; set; }
        public int Forbidden { get; set; }
        public bool Success { get { return Forbidden == 0; } }
    }

    /// <summary>
    /// Verifies that the published Part has no dependency on another CAD model.
    /// A company bend/gauge table is a manufacturing rule resource, not geometry
    /// ownership. It is accepted only when the exact path is declared by a native
    /// Sheet Metal feature in the output. Other spreadsheets (for example design
    /// tables) and all unclassified dependencies remain forbidden.
    /// </summary>
    public static class ExternalDependencyAuditV7
    {
        public static ExternalDependencyAuditResultV7 Run(ModelDoc2 model)
        {
            if (model == null) throw new ArgumentNullException("model");

            HashSet<string> sheetMetalResources = CollectSheetMetalResources(model);
            foreach (string resource in sheetMetalResources.OrderBy(value => value, StringComparer.OrdinalIgnoreCase))
                MirrorV7Diagnostics.Log("[PHASE6B][SHEET_METAL_RESOURCE] path=\"" + resource + "\"");

            object dependencyData = model.Extension.GetDependencies(true, false, false, false, false);
            Array raw = dependencyData as Array;
            if (dependencyData != null && (raw == null || raw.Rank != 1))
                throw new InvalidOperationException("Dependency API returned an invalid array; independence cannot be verified.");
            string[] values = raw == null
                ? new string[0]
                : raw.Cast<object>().Select(value => Convert.ToString(value) ?? "").ToArray();
            if (values.Length % 2 != 0)
                throw new InvalidOperationException("Dependency API returned an incomplete name/path pair; independence cannot be verified.");

            var result = new ExternalDependencyAuditResultV7();
            for (int i = 0, dependencyIndex = 0; i < values.Length; i += 2, dependencyIndex++)
            {
                string displayName = values[i] ?? "";
                string path = i + 1 < values.Length ? values[i + 1] ?? "" : displayName;
                string normalized = NormalizePath(path);
                bool isAllowedSheetMetalResource =
                    IsSheetMetalTableFile(normalized) && sheetMetalResources.Contains(normalized);

                result.Total++;
                if (isAllowedSheetMetalResource)
                {
                    result.AllowedSheetMetalResources++;
                    MirrorV7Diagnostics.Log("[PHASE6B][DEPENDENCY_ALLOWED] index=" + dependencyIndex +
                        " name=\"" + displayName + "\" path=\"" + path +
                        "\" classification=SheetMetalManufacturingTable");
                }
                else
                {
                    result.Forbidden++;
                    MirrorV7Diagnostics.Log("[PHASE6B][DEPENDENCY_FORBIDDEN] index=" + dependencyIndex +
                        " name=\"" + displayName + "\" path=\"" + path +
                        "\" normalized=\"" + normalized + "\"");
                }
            }

            MirrorV7Diagnostics.Log("[PHASE6B][DEPENDENCY_SUMMARY] total=" + result.Total +
                " allowedSheetMetalResources=" + result.AllowedSheetMetalResources +
                " forbidden=" + result.Forbidden + " result=" + (result.Success ? "PASS" : "FAIL"));
            return result;
        }

        private static HashSet<string> CollectSheetMetalResources(ModelDoc2 model)
        {
            var result = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            MirrorV7ModelGraph graph = FeatureTreeScannerV7.Scan(model);
            foreach (MirrorV7FeatureNode node in graph.Nodes)
            {
                if (node == null || node.Feature == null) continue;
                object definition;
                try { definition = node.Feature.GetDefinition(); }
                catch { continue; }
                if (definition == null) continue;

                ISheetMetalFeatureData sheetMetal = definition as ISheetMetalFeatureData;
                if (sheetMetal != null)
                {
#pragma warning disable 618
                    TryAdd(result, delegate { return sheetMetal.BendTableFile; });
#pragma warning restore 618
                    TryAddCustom(result, delegate { return sheetMetal.GetCustomBendAllowance(); });
                    try
                    {
                        bool useGaugeTable;
                        string gaugeTablePath;
                        sheetMetal.GetUseGaugeTable(out useGaugeTable, out gaugeTablePath);
                        if (useGaugeTable) AddPath(result, gaugeTablePath);
                    }
                    catch { }
                    continue;
                }

                IBendsFeatureData bends = definition as IBendsFeatureData;
                if (bends != null)
                {
#pragma warning disable 618
                    TryAdd(result, delegate { return bends.BendTableFile; });
#pragma warning restore 618
                    TryAddCustom(result, delegate { return bends.GetCustomBendAllowance(); });
                    continue;
                }

                IOneBendFeatureData oneBend = definition as IOneBendFeatureData;
                if (oneBend != null)
                {
#pragma warning disable 618
                    TryAdd(result, delegate { return oneBend.BendTableFile; });
#pragma warning restore 618
                    TryAddCustom(result, delegate { return oneBend.GetCustomBendAllowance(); });
                }
            }
            return result;
        }

        private static void TryAdd(HashSet<string> target, Func<string> getter)
        {
            try { AddPath(target, getter()); }
            catch { }
        }

        private static void TryAddCustom(HashSet<string> target, Func<CustomBendAllowance> getter)
        {
            try
            {
                CustomBendAllowance allowance = getter();
                if (allowance != null) AddPath(target, allowance.BendTableFile);
            }
            catch { }
        }

        private static void AddPath(HashSet<string> target, string path)
        {
            string normalized = NormalizePath(path);
            if (IsSheetMetalTableFile(normalized)) target.Add(normalized);
        }

        private static bool IsSheetMetalTableFile(string path)
        {
            string extension;
            try { extension = Path.GetExtension(path) ?? ""; }
            catch { return false; }
            return extension.Equals(".xls", StringComparison.OrdinalIgnoreCase) ||
                   extension.Equals(".xlsx", StringComparison.OrdinalIgnoreCase) ||
                   extension.Equals(".csv", StringComparison.OrdinalIgnoreCase) ||
                   extension.Equals(".txt", StringComparison.OrdinalIgnoreCase) ||
                   extension.Equals(".btl", StringComparison.OrdinalIgnoreCase);
        }

        private static string NormalizePath(string path)
        {
            if (string.IsNullOrWhiteSpace(path)) return "";
            string value = System.Environment.ExpandEnvironmentVariables(path.Trim().Trim('"'));
            try { return Path.GetFullPath(value).TrimEnd(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar); }
            catch { return value; }
        }
    }

    public sealed class ExternalReferenceBreakResultV7
    {
        public int Before { get; set; }
        public int After { get; set; }
        public bool Executed { get; set; }
        public int ForbiddenBefore { get; set; }
        public int ForbiddenAfter { get; set; }
        // In-memory result only. The publication caller must save/reopen and audit again.
        public bool Success { get { return Executed && After == 0 && ForbiddenAfter == 0; } }
    }

    /// <summary>
    /// Freezes native in-context model references in the disposable output Part.
    /// This is intentionally executed only after feature replay and geometry
    /// validation. It never runs on the source document. InsertFeatures is false
    /// so the existing native feature tree is retained instead of importing a
    /// second feature set from the referenced model.
    /// </summary>
    public static class ExternalReferenceBreakServiceV7
    {
        public static ExternalReferenceBreakResultV7 Run(ModelDoc2 model, ModelDoc2 source)
        {
            if (model == null) throw new ArgumentNullException("model");
            if (source == null) throw new ArgumentNullException("source");
            if (model.GetType() != (int)SolidWorks.Interop.swconst.swDocumentTypes_e.swDocPART ||
                string.IsNullOrWhiteSpace(source.GetPathName()) ||
                SingleSketchTargetBuilderV7.SameComObject(model, source) ||
                (!string.IsNullOrWhiteSpace(model.GetPathName()) &&
                 string.Equals(Path.GetFullPath(model.GetPathName()), Path.GetFullPath(source.GetPathName()),
                     StringComparison.OrdinalIgnoreCase)))
                throw new InvalidOperationException("External reference detachment is allowed only on a separate output Part, never on the source.");
            ModelDocExtension extension = model.Extension;
            ExternalDependencyAuditResultV7 dependencies = ExternalDependencyAuditV7.Run(model);
            var result = new ExternalReferenceBreakResultV7
            {
                Before = extension.ListExternalFileReferencesCount(),
                ForbiddenBefore = dependencies.Forbidden
            };
            MirrorV7Diagnostics.Log("[FEATURE43][DETACH_BEGIN] part=\"" + model.GetPathName() +
                "\" listedReferences=" + result.Before + " forbiddenDependencies=" + result.ForbiddenBefore);
            if (result.Before < 0) throw new InvalidOperationException("Invalid external reference count.");
            if (result.Before == 0 && dependencies.Success) return result;

            // GetDependencies and ListExternalFileReferences enumerate different data.
            // A zero list count must not suppress detachment of a known CAD dependency.
            // Collect owner diagnostics BEFORE any mutation, including the zero-count case.
            LogExternalReferenceDetails(extension, result.Before);
            LogReferenceOwners(model);
            model.ClearSelection2(true);
            extension.BreakAllExternalFileReferences2(false);
            result.Executed = true;
            MirrorV7Diagnostics.Log("[PHASE6C][BREAK_EXECUTED] insertFeatures=False sourceDocumentModified=False");

            if (!model.EditRebuild3())
                throw new InvalidOperationException("External references were broken but the output Part did not rebuild.");

            result.After = extension.ListExternalFileReferencesCount();
            result.ForbiddenAfter = ExternalDependencyAuditV7.Run(model).Forbidden;
            MirrorV7Diagnostics.Log("[PHASE6C][EXTERNAL_REFERENCE_COUNT] after=" + result.After +
                " forbiddenDependencies=" + result.ForbiddenAfter + " finalVerification=SAVE_REOPEN_REQUIRED");
            if (result.After != 0)
                LogExternalReferenceDetails(extension, result.After);
            return result;
        }

        private static void LogReferenceOwners(ModelDoc2 model)
        {
            int owners = 0, failures = 0;
            foreach (MirrorV7FeatureNode node in FeatureTreeScannerV7.Scan(model).Nodes)
            {
                if (node == null || node.Feature == null) continue;
                try
                {
                    int count = node.Feature.ListExternalFileReferencesCount();
                    if (count <= 0) continue;
                    owners++;
                    object paths, components, features, types, statuses, entities, featureComponents;
                    int configOption;
                    string configName;
                    node.Feature.ListExternalFileReferences2(out paths, out components, out features,
                        out types, out statuses, out entities, out featureComponents, out configOption, out configName);
                    for (int i = 0; i < count; i++)
                        MirrorV7Diagnostics.Log("[FEATURE43][REFERENCE_OWNER] name=\"" + node.Name +
                            "\" type=\"" + node.TypeName + "\" model=\"" + ValueAt(paths, i) +
                            "\" component=\"" + ValueAt(components, i) + "\" status=\"" + ValueAt(statuses, i) +
                            "\" entity=\"" + ValueAt(entities, i) + "\" configuration=\"" + configName + "\"");
                }
                catch (Exception ex)
                {
                    failures++;
                    MirrorV7Diagnostics.Log("[FEATURE43][OWNER_QUERY_FAILED] name=\"" + node.Name + "\" reason=" + ex.Message);
                }
            }
            try
            {
                int count = model.ListAuxiliaryExternalFileReferencesCount();
                object features, paths;
                model.ListAuxiliaryExternalFileReferences(out features, out paths);
                for (int i = 0; i < count; i++)
                    MirrorV7Diagnostics.Log("[FEATURE43][AUXILIARY_REFERENCE] feature=\"" +
                        ValueAt(features, i) + "\" path=\"" + ValueAt(paths, i) + "\"");
            }
            catch (Exception ex)
            {
                failures++;
                MirrorV7Diagnostics.Log("[FEATURE43][AUXILIARY_QUERY_FAILED] reason=" + ex.Message);
            }
            MirrorV7Diagnostics.Log("[FEATURE43][OWNER_SUMMARY] owners=" + owners +
                " queryFailures=" + failures + " zeroOwnersDoesNotProveIndependence=True");
        }

        private static void LogExternalReferenceDetails(ModelDocExtension extension, int expectedCount)
        {
            try
            {
                object modelPaths, componentPaths, features, dataTypes, statuses,
                    referenceEntities, featureComponents, configOptions, configNames;
                extension.ListExternalFileReferences2(out modelPaths, out componentPaths, out features,
                    out dataTypes, out statuses, out referenceEntities, out featureComponents,
                    out configOptions, out configNames);
                Array returnedPaths = modelPaths as Array;
                expectedCount = Math.Max(expectedCount, returnedPaths == null ? 0 : returnedPaths.Length);
                for (int i = 0; i < expectedCount; i++)
                {
                    MirrorV7Diagnostics.Log("[PHASE6C][EXTERNAL_REFERENCE] index=" + i +
                        " model=\"" + ValueAt(modelPaths, i) + "\" component=\"" + ValueAt(componentPaths, i) +
                        "\" feature=\"" + ValueAt(features, i) + "\" dataType=\"" + ValueAt(dataTypes, i) +
                        "\" status=\"" + ValueAt(statuses, i) + "\" entity=\"" + ValueAt(referenceEntities, i) +
                        "\" featureComponent=\"" + ValueAt(featureComponents, i) + "\"");
                }
            }
            catch (Exception ex)
            {
                MirrorV7Diagnostics.Log("[PHASE6C][EXTERNAL_REFERENCE_DETAIL_UNAVAILABLE] message=" + ex.Message);
            }
        }

        private static string ValueAt(object values, int index)
        {
            Array array = values as Array;
            if (array == null || index < 0 || index >= array.Length) return "";
            try { return Convert.ToString(array.GetValue(array.GetLowerBound(0) + index)) ?? ""; }
            catch { return ""; }
        }
    }
}
